language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements-py3.txt --allow-external pydot .; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements.txt     --allow-unverified pydot --allow-unverified python-graph-core --allow-unverified python-graph-dot .; fi
# command to run tests
script: nosetests
