language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements-py3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements.txt; fi
# command to run tests
script: nosetests
